# Generated by Django 5.0.6 on 2024-07-18 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forsale', '0004_items_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('accepted', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forsale.items')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='forsale.userinfo')),
            ],
        ),
    ]
