# Generated by Django 5.0.6 on 2024-07-22 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forsale', '0005_offers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offers',
            old_name='user',
            new_name='userinfo',
        ),
    ]
