# Generated by Django 5.0.6 on 2024-07-24 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forsale', '0006_rename_user_offers_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='forsale.items'),
        ),
    ]
