# Generated by Django 5.0.6 on 2024-08-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forsale', '0007_alter_offers_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='sold',
        ),
        migrations.AddConstraint(
            model_name='offers',
            constraint=models.UniqueConstraint(condition=models.Q(('accepted', True)), fields=('item',), name='accepted_unique'),
        ),
    ]
